export const tableDataVerbos = [
  {
    id: 1,
    verbo: "ονομάζω",
    traduccion: "nombrar",
    aoristo: "ονόμασα",
    futuro: "θα ονομάσω",
    ypotaktiki: "να ονομάσω",
    imperativo: "",
  },
  {
    id: 2,
    verbo: "σκέφτομαι",
    traduccion: "pensar",
    aoristo: "σκεφτηκά",
    futuro: "θα σκεφτώ",
    ypotaktiki: "να σκεφτώ",
    imperativo: "",
  },
  {
    id: 3,
    verbo: "επιστρέφω",
    traduccion: "volver",
    aoristo: "επέστρεψα",
    futuro: "θα επιστρέψω",
    ypotaktiki: "να επιστρέψω",
    imperativo: "",
  },
  {
    id: 4,
    verbo: "ζω",
    traduccion: "vivir",
    aoristo: "έζησα",
    futuro: "θα ζήσω",
    ypotaktiki: "να ζήσω",
    imperativo: "",
  },
  {
    id: 5,
    verbo: "αφήνω",
    traduccion: "dejar",
    aoristo: "άφησα",
    futuro: "θα αφήσω",
    ypotaktiki: "να αφήσω",
    imperativo: "",
  },
  {
    id: 6,
    verbo: "ακολουθάω",
    traduccion: "seguir a",
    aoristo: "ακολούθησα",
    futuro: "θα ακολουθήσω",
    ypotaktiki: "να ακολουθήσω",
    imperativo: "",
  },
  {
    id: 7,
    verbo: "γνωρίζω",
    traduccion: "conocer",
    aoristo: "γνώρισα",
    futuro: "θα γνωρίσω",
    ypotaktiki: "να γνωρίσω",
    imperativo: "",
  },
  {
    id: 8,
    verbo: "μπορώ",
    traduccion: "poder",
    aoristo: "μπόρεσα",
    futuro: "θα μπορέσω",
    ypotaktiki: "να μπορέσω",
    imperativo: "",
  },
  {
    id: 9,
    verbo: "υπάρχω",
    traduccion: "haber, existir",
    aoristo: "υπήρξα",
    futuro: "θα υπάρξω",
    ypotaktiki: "να υπάρξω",
    imperativo: "",
  },
  {
    id: 10,
    verbo: "φτάνω",
    traduccion: "llegar",
    aoristo: "έφτασα",
    futuro: "θα φτάσω",
    ypotaktiki: "να φτάσω",
    imperativo: "",
  },
  {
    id: 11,
    verbo: "ξέρω",
    traduccion: "saber",
    aoristo: "ήξερα",
    futuro: "θα ξέρω",
    ypotaktiki: "να ξέρω",
    imperativo: "",
  },
  {
    id: 12,
    verbo: "πρέπει",
    traduccion: "deber, tener que",
    aoristo: "έπρεπε",
    futuro: "θα πρέπει",
    ypotaktiki: "να πρέπει",
    imperativo: "",
  },
  {
    id: 13,
    verbo: "νομίζω",
    traduccion: "creer",
    aoristo: "νόμισα",
    futuro: "θα νομίσω",
    ypotaktiki: "να νομίσω",
    imperativo: "",
  },
  {
    id: 14,
    verbo: "μιλάω",
    traduccion: "hablar",
    aoristo: "μίλησα",
    futuro: "θα μιλήσω",
    ypotaktiki: "να μιλήσω",
    imperativo: "",
  },
  {
    id: 15,
    verbo: "μένω",
    traduccion: "quedarse",
    aoristo: "έμεινα",
    futuro: "θα μείνω",
    ypotaktiki: "να μείνω",
    imperativo: "",
  },
  {
    id: 16,
    verbo: "στέλνω",
    traduccion: "enviar",
    aoristo: "έστειλα",
    futuro: "θα στείλω",
    ypotaktiki: "να στείλω",
    imperativo: "",
  },
  {
    id: 17,
    verbo: "δίνω",
    traduccion: "dar",
    aoristo: "έδωσα",
    futuro: "θα δώσω",
    ypotaktiki: "να δώσω",
    imperativo: "",
  },
  {
    id: 18,
    verbo: "βλέπω",
    traduccion: "ver",
    aoristo: "είδα",
    futuro: "θα δω",
    ypotaktiki: "να δω",
    imperativo: "",
  },
  {
    id: 19,
    verbo: "λεω",
    traduccion: "decir",
    aoristo: "είπα",
    futuro: "θα πω",
    ypotaktiki: "να πω",
    imperativo: "",
  },
  {
    id: 20,
    verbo: "πάω, πηγαίνω",
    traduccion: "ir",
    aoristo: "πήγα",
    futuro: "θα πάω",
    ypotaktiki: "να πάω",
    imperativo: "",
  },
  {
    id: 21,
    verbo: "τρώω",
    traduccion: "comer",
    aoristo: "έφαγα",
    futuro: "θα φάω",
    ypotaktiki: "να φάω",
    imperativo: "",
  },
  {
    id: 22,
    verbo: "καταλαβαίνω",
    traduccion: "entender",
    aoristo: "κατάλαβα",
    futuro: "θα καταλάβω",
    ypotaktiki: "να καταλάβω",
    imperativo: "",
  },
  {
    id: 23,
    verbo: "περιμένω",
    traduccion: "esperar",
    aoristo: "περίμενα",
    futuro: "θα περιμένω",
    ypotaktiki: "να περιμένω",
    imperativo: "",
  },
  {
    id: 24,
    verbo: "έχω",
    traduccion: "tener",
    aoristo: "είχα",
    futuro: "θα έχω",
    ypotaktiki: "να έχω",
    imperativo: "",
  },
  {
    id: 25,
    verbo: "θέλω",
    traduccion: "querer",
    aoristo: "ήθελα",
    futuro: "θα θέλω",
    ypotaktiki: "να θέλω",
    imperativo: "",
  },
  {
    id: 26,
    verbo: "έρχομαι",
    traduccion: "venir",
    aoristo: "ήρθα",
    futuro: "θα έρθω",
    ypotaktiki: "να έρθω",
    imperativo: "",
  },
  {
    id: 27,
    verbo: "πίνω",
    traduccion: "beber",
    aoristo: "ήπια",
    futuro: "θα πιω",
    ypotaktiki: "να πιω",
    imperativo: "",
  },
  {
    id: 28,
    verbo: "βρίσκω",
    traduccion: "encontrar",
    aoristo: "βρήκα",
    futuro: "θα βρω",
    ypotaktiki: "να βρω",
    imperativo: "",
  },
  {
    id: 29,
    verbo: "κοιμάμαι",
    traduccion: "dormir",
    aoristo: "κοιμήθηκα",
    futuro: "θα κοιμηθώ",
    ypotaktiki: "να κοιμηθώ",
    imperativo: "",
  },
  {
    id: 30,
    verbo: "θυμάμαι",
    traduccion: "recordar",
    aoristo: "θυμήθηκα",
    futuro: "θα θυμηθώ",
    ypotaktiki: "να θυμηθώ",
    imperativo: "",
  },
  {
    id: 31,
    verbo: "είμαι",
    traduccion: "ser",
    aoristo: "ήμουνα",
    futuro: "θα είμαι",
    ypotaktiki: "να είμαι",
    imperativo: "",
  },
  {
    id: 32,
    verbo: "κάνω",
    traduccion: "hacer",
    aoristo: "έκανα",
    futuro: "θα κάνω",
    ypotaktiki: "να κάνω",
    imperativo: "",
  },
  {
    id: 33,
    verbo: "παίρνω",
    traduccion: "tomar, coger",
    aoristo: "πήρα",
    futuro: "θα πάρω",
    ypotaktiki: "να πάρω",
    imperativo: "",
  },
  {
    id: 34,
    verbo: "περνάω",
    traduccion: "pasar",
    aoristo: "πέρασα",
    futuro: "θα περάσω",
    ypotaktiki: "να περάσω",
    imperativo: "",
  },
  {
    id: 35,
    verbo: "φέρνω",
    traduccion: "traer",
    aoristo: "έφερα",
    futuro: "θα φέρω",
    ypotaktiki: "να φέρω",
    imperativo: "",
  },
  {
    id: 36,
    verbo: "φεύγω",
    traduccion: "irse, marcharse",
    aoristo: "έφυγα",
    futuro: "θα φύγω",
    ypotaktiki: "να φύγω",
    imperativo: "",
  },
  {
    id: 37,
    verbo: "κάθομαι",
    traduccion: "sentarse, estar sentado",
    aoristo: "κάθισα",
    futuro: "θα καθισώ",
    ypotaktiki: "να καθισώ",
    imperativo: "",
  },
  {
    id: 38,
    verbo: "γίνομαι",
    traduccion: "llegar a ser, convertirse, suceder",
    aoristo: "έγινα",
    futuro: "θα γίνω",
    ypotaktiki: "να γίνω",
    imperativo: "",
  },
  {
    id: 39,
    verbo: "φαίνομαι",
    traduccion: "parecer",
    aoristo: "φάνικα",
    futuro: "θα φάνω",
    ypotaktiki: "να φάνω",
    imperativo: "",
  },
  {
    id: 40,
    verbo: "βάζω",
    traduccion: "poner",
    aoristo: "έβαλα",
    futuro: "θα βάλω",
    ypotaktiki: "να βάλω",
    imperativo: "",
  },
  {
    id: 41,
    verbo: "βγάζω",
    traduccion: "quitar, sacar",
    aoristo: "έβγαλα",
    futuro: "θα βγάλω",
    ypotaktiki: "να βγάλω",
    imperativo: "",
  },
  {
    id: 42,
    verbo: "βγαίνω",
    traduccion: "salir",
    aoristo: "βγήκα",
    futuro: "θα βγω",
    ypotaktiki: "να βγω",
    imperativo: "",
  },
  {
    id: 43,
    verbo: "μπάινω",
    traduccion: "entrar",
    aoristo: "μπήκα",
    futuro: "θα μπω",
    ypotaktiki: "να μπω",
    imperativo: "",
  },
  {
    id: 44,
    verbo: "ανεβαίνω",
    traduccion: "subir",
    aoristo: "ανέβηκα",
    futuro: "θα ανεβώ",
    ypotaktiki: "να ανεβώ",
    imperativo: "",
  },
  {
    id: 45,
    verbo: "κατεβαίνω",
    traduccion: "bajar",
    aoristo: "κατέβηκα",
    futuro: "θα κατεβώ",
    ypotaktiki: "να κατεβώ",
    imperativo: "",
  },
  {
    id: 46,
    verbo: "πλένω",
    traduccion: "lavar",
    aoristo: "έπλυνα",
    futuro: "θα πλύνω",
    ypotaktiki: "να πλύνω",
    imperativo: "",
  },
  {
    id: 47,
    verbo: "ζητάω",
    traduccion: "pedir",
    aoristo: "ζήτησα",
    futuro: "θα ζητήσω",
    ypotaktiki: "να ζητήσω",
    imperativo: "",
  },
  {
    id: 48,
    verbo: "παίζω",
    traduccion: "jugar",
    aoristo: "έπαιξα",
    futuro: "θα παίξω",
    ypotaktiki: "να παίξω",
    imperativo: "",
  },
  {
    id: 49,
    verbo: "συμβαίνω",
    traduccion: "ocurrir",
    aoristo: "συνέβηκα",
    futuro: "θα σύνβω",
    ypotaktiki: "να σύνβω",
    imperativo: "",
  },
  {
    id: 50,
    verbo: "παράγω",
    traduccion: "producir",
    aoristo: "πάρηγα",
    futuro: "θα παράγω",
    ypotaktiki: "να παράγω",
    imperativo: "",
  },
  {
    id: 51,
    verbo: "νιώθω",
    traduccion: "sentir",
    aoristo: "ένισα",
    futuro: "θα νιώσω",
    ypotaktiki: "να νιώσω",
    imperativo: "",
  },
  {
    id: 52,
    verbo: "μεταxειρίζομαι",
    traduccion: "tratar",
    aoristo: "μεταχειρίστικα",
    futuro: "θα μεταχειριστώ",
    ypotaktiki: "να μεταχειριστώ",
    imperativo: "",
  },
  {
    id: 53,
    verbo: "κοιτάζω",
    traduccion: "mirar",
    aoristo: "κοίταξα",
    futuro: "θα κοιτάξω",
    ypotaktiki: "να κοιτάξω",
    imperativo: "",
  },
  {
    id: 54,
    verbo: "μετράω",
    traduccion: "medir, contar",
    aoristo: "μέτρησα",
    futuro: "θα μετρήσω",
    ypotaktiki: "να μετρήσω",
    imperativo: "",
  },
  {
    id: 55,
    verbo: "αρχίζω",
    traduccion: "empezar, comenzar",
    aoristo: "άρχισα",
    futuro: "θα αρχίσω",
    ypotaktiki: "να αρχίσω",
    imperativo: "",
  },
  {
    id: 56,
    verbo: "αναζητώ",
    traduccion: "buscar",
    aoristo: "αναζήτησα",
    futuro: "θα αναζητήσω",
    ypotaktiki: "να αναζητήσω",
    imperativo: "",
  },
  {
    id: 57,
    verbo: "δουλέυω",
    traduccion: "trabajar",
    aoristo: "δούλεψα",
    futuro: "θα δουλέψω",
    ypotaktiki: "να δουλέψω",
    imperativo: "",
  },
  {
    id: 58,
    verbo: "γράφω",
    traduccion: "escribir",
    aoristo: "έγραψα",
    futuro: "θα γράψω",
    ypotaktiki: "να γράψω",
    imperativo: "",
  },
  {
    id: 59,
    verbo: "διαβάζω",
    traduccion: "leer, estudiar",
    aoristo: "διάβασα",
    futuro: "θα διαβάσω",
    ypotaktiki: "να διαβάσω",
    imperativo: "",
  },
  {
    id: 60,
    verbo: "χάνω",
    traduccion: "perder",
    aoristo: "έχασα",
    futuro: "θα χάσω",
    ypotaktiki: "να χάσω",
    imperativo: "",
  },
  {
    id: 61,
    verbo: "δέχομαι",
    traduccion: "recibir",
    aoristo: "δέχτηκα",
    futuro: "θα δεχτώ",
    ypotaktiki: "να δεχτώ",
    imperativo: "",
  },
  {
    id: 62,
    verbo: "κουνάω",
    traduccion: "mover",
    aoristo: "κούνησα",
    futuro: "θα κουνήσω",
    ypotaktiki: "να κουνήσω",
    imperativo: "",
  },
  {
    id: 63,
    verbo: "κινούμαι",
    traduccion: "moverse",
    aoristo: "κινήθηκα",
    futuro: "θα κινηθώ",
    ypotaktiki: "να κινηθώ",
    imperativo: "",
  },
  {
    id: 64,
    verbo: "σερβίρω",
    traduccion: "servir",
    aoristo: "σέρβιρα",
    futuro: "θα σερβίρω",
    ypotaktiki: "να σερβίρω",
    imperativo: "",
  },
  {
    id: 65,
    verbo: "αποχτώ",
    traduccion: "conseguir",
    aoristo: "απόχτησα",
    futuro: "θα αποχτήσω",
    ypotaktiki: "να αποχτήσω",
    imperativo: "",
  },
  {
    id: 66,
    verbo: "εμφανίζομαι",
    traduccion: "aparecer",
    aoristo: "εμφανίστηκα",
    futuro: "θα εμφανιστώ",
    ypotaktiki: "να εμφανιστώ",
    imperativo: "",
  },
  {
    id: 67,
    verbo: "τελειώνω",
    traduccion: "terminar",
    aoristo: "τελείωσα",
    futuro: "θα τελειώσω",
    ypotaktiki: "να τελειώσω",
    imperativo: "",
  },
  {
    id: 68,
    verbo: "χρειάζομαι",
    traduccion: "necesitar",
    aoristo: "χρειάστηκα",
    futuro: "θα χρειαστώ",
    ypotaktiki: "να χρειαστώ",
    imperativo: "",
  },
  {
    id: 69,
    verbo: "συντηρώ",
    traduccion: "mantener",
    aoristo: "συντήρησα",
    futuro: "θα συντηρήσω",
    ypotaktiki: "να συντηρήσω",
    imperativo: "",
  },
  // ρε μαλάκα
  { 
    id: 70,
    verbo: "αποβαίνω",
    traduccion: "resultar",
    aoristo: "απέβηκα",
    futuro: "θα απόβω",
    ypotaktiki: "να απόβω",
    imperativo: "",
  },
  {
    id: 71,
    verbo: "πέφτω",
    traduccion: "caer",
    aoristo: "έπεσα",
    futuro: "θα πέσω",
    ypotaktiki: "να πέσω",
    imperativo: "",
  },
  {
    id: 72,
    verbo: "αλλάζω",
    traduccion: "cambiar",
    aoristo: "άλλαξα",
    futuro: "θα αλλάξω",
    ypotaktiki: "να αλλάξω",
    imperativo: "",
  },
  {
    id: 73,
    verbo: "αλλάζω",
    traduccion: "cambiar",
    aoristo: "άλλαξα",
    futuro: "θα αλλάξω",
    ypotaktiki: "να αλλάξω",
    imperativo: "",
  },
  {
    id: 74,
    verbo: "δημιουργώ",
    traduccion: "crear",
    aoristo: "δημιούργησα",
    futuro: "θα δημιουργήσω",
    ypotaktiki: "να δημιουργήσω",
    imperativo: "",
  },
  {
    id: 75,
    verbo: "ανοίγω",
    traduccion: "abrir",
    aoristo: "άνοιξα",
    futuro: "θα ανοίξω",
    ypotaktiki: "να ανοίξω",
    imperativo: "",
  },
  {
    id: 76,
    verbo: "κλείνω",
    traduccion: "cerrar",
    aoristo: "έκλεισα",
    futuro: "θα κλείδω",
    ypotaktiki: "να κλείδω",
    imperativo: "",
  },
  {
    id: 77,
    verbo: "ακούω",
    traduccion: "oir",
    aoristo: "άκουσα",
    futuro: "θα ακούσω",
    ypotaktiki: "να ακούσω",
    imperativo: "",
  },
  {
    id: 78,
    verbo: "ονειρεύομαι",
    traduccion: "soñar",
    aoristo: "ονειρεύτηκα",
    futuro: "θα ονειρευτώ",
    ypotaktiki: "να ονειρευτώ",
    imperativo: "",
  },
  {
    id: 79,
    verbo: "μετατρέπω",
    traduccion: "convertir",
    aoristo: "μετάτρεψα",
    futuro: "θα μετατρέψω",
    ypotaktiki: "να μετατρέψω",
    imperativo: "",
  },
  {
    id: 80,
    verbo: "μετατρέπω",
    traduccion: "convertir",
    aoristo: "μετάτρεψα",
    futuro: "θα μετατρέψω",
    ypotaktiki: "να μετατρέψω",
    imperativo: "",
  },
  {
    id: 81,
    verbo: "κερδίζω",
    traduccion: "ganar",
    aoristo: "κέρδισα",
    futuro: "θα κερδίσω",
    ypotaktiki: "να κερδίσω",
    imperativo: "",
  },
  {
    id: 82,
    verbo: "σχηματίζω",
    traduccion: "formar",
    aoristo: "σχημάτισα",
    futuro: "θα σχηματίσω",
    ypotaktiki: "να σχηματίσω",
    imperativo: "",
  },
  {
    id: 83,
    verbo: "φεύγω",
    traduccion: "partir, marcharse, irse",
    aoristo: "εφύρα",
    futuro: "θα φύρω",
    ypotaktiki: "να φύρω",
    imperativo: "",
  },
  {
    id: 84,
    verbo: "υποθέτω",
    traduccion: "suponer",
    aoristo: "υπέθεσα",
    futuro: "θα υποθέσω",
    ypotaktiki: "να υποθέσω",
    imperativo: "",
  },
  {
    id: 85,
    verbo: "πεθαίνω",
    traduccion: "morir",
    aoristo: "πέθανα",
    futuro: "θα πεθάνω",
    ypotaktiki: "να πεθάνω",
    imperativo: "",
  },
  {
    id: 86,
    verbo: "αποδέχομαι",
    traduccion: "aceptar",
    aoristo: "αποδέχτηκα",
    futuro: "θα αποδεχτώ",
    ypotaktiki: "να αποδεχτώ",
    imperativo: "",
  },
  {
    id: 87,
    verbo: "επιτελώ",
    traduccion: "realizar",
    aoristo: "επιτέλεσα",
    futuro: "θα επιτελέσω",
    ypotaktiki: "να επιτελέσω",
    imperativo: "",
  },
  {
    id: 88,
    verbo: "σπούδάζω",
    traduccion: "estudiar, cursar estudios",
    aoristo: "σπούδασα",
    futuro: "θα σπουδάσω",
    ypotaktiki: "να σπουδάσω",
    imperativo: "",
  },
  {
    id: 89,
    verbo: "απαντάω",
    traduccion: "responder",
    aoristo: "απάντησα",
    futuro: "θα απαντήσω",
    ypotaktiki: "να απαντήσω",
    imperativo: "",
  },
  {
    id: 91,
    verbo: "λαμβάνω",
    traduccion: "lograr",
    aoristo: "έλαβα",
    futuro: "θα λάβω",
    ypotaktiki: "να λάβω",
    imperativo: "",
  },
  {
    id: 92,
    verbo: "εξηγώ",
    traduccion: "explicar",
    aoristo: "εξήγησα",
    futuro: "θα εξηγήσω",
    ypotaktiki: "να εξηγήσω",
    imperativo: "",
  },
  {
    id: 93,
    verbo: "ρωτάω",
    traduccion: "preguntar",
    aoristo: "ρώτησα",
    futuro: "θα ρωτήσω",
    ypotaktiki: "να ρωτήσω",
    imperativo: "",
  },
  {
    id: 94,
    verbo: "αγγίζω",
    traduccion: "tocar",
    aoristo: "άγγιξα",
    futuro: "θα αγγίξω",
    ypotaktiki: "να αγγίξω",
    imperativo: "",
  },
  {
    id: 95,
    verbo: "γέννεμαι",
    traduccion: "nacer",
    aoristo: "γεννήθηκα",
    futuro: "θα γεννηθώ",
    ypotaktiki: "να γεννηθώ",
    imperativo: "",
  },
  {
    id: 96,
    verbo: "πιδάω",
    traduccion: "saltar",
    aoristo: "πήδηξα",
    futuro: "θα πηδήσω",
    ypotaktiki: "να πηδήσω",
    imperativo: "",
  },
  {
    id: 97,
    verbo: "φθάνομαι",
    traduccion: "alcanzar",
    aoristo: "φθάστηκα",
    futuro: "θα φθαστώ",
    ypotaktiki: "να φθαστώ",
    imperativo: "",
  },
  {
    id: 98,
    verbo: "μισώ",
    traduccion: "odiar",
    aoristo: "μίσησα",
    futuro: "θα μισήσω",
    ypotaktiki: "να μισήσω",
    imperativo: "",
  },
  {
    id: 99,
    verbo: "αγαπάω",
    traduccion: "amar",
    aoristo: "αγάπησα",
    futuro: "θα αγαπήσω",
    ypotaktiki: "να αγαπήσω",
    imperativo: "",
  },
  {
    id: 100,
    verbo: "βοηθάω",
    traduccion: "ayudar",
    aoristo: "βοήθησα",
    futuro: "θα βοηθήσω",
    ypotaktiki: "να βοηθήσω",
    imperativo: "",
  },
  {
    id: 101,
    verbo: "αποφασίζω",
    traduccion: "decidir",
    aoristo: "αποφάσισα",
    futuro: "θα αποφασίσω",
    ypotaktiki: "να αποφασίσω",
    imperativo: "",
  },
  {
    id: 102,
    verbo: "ταξιδεύω",
    traduccion: "viajar",
    aoristo: "ταξίδεψα",
    futuro: "θα ταξιδέψω",
    ypotaktiki: "να ταξιδέψω",
    imperativo: "",
  },
  {
    id: 103,
    verbo: "τραγουδάω",
    traduccion: "cantar",
    aoristo: "τραγούδησα",
    futuro: "θα τραγουδήσω",
    ypotaktiki: "να τραγουδήσω",
    imperativo: "",
  },
  {
    id: 104,
    verbo: "νικώ",
    traduccion: "vencer",
    aoristo: "νίκησα",
    futuro: "θα νικήσω",
    ypotaktiki: "να νικήσω",
    imperativo: "",
  },
  {
    id: 105,
    verbo: "κολυμπάω",
    traduccion: "nadar",
    aoristo: "κολύμπησα",
    futuro: "θα κολυμπήσω",
    ypotaktiki: "να κολυμπήσω",
    imperativo: "",
  },
  {
    id: 106,
    verbo: "πονάω",
    traduccion: "doler",
    aoristo: "πόνησα",
    futuro: "θα πονήσω",
    ypotaktiki: "να πονήσω",
    imperativo: "",
  },
  {
    id: 107,
    verbo: "γελάω",
    traduccion: "reír",
    aoristo: "γέλασα",
    futuro: "θα γελάσω",
    ypotaktiki: "να γελάσω",
    imperativo: "",
  },
  {
    id: 108,
    verbo: "ξεχνάω",
    traduccion: "olvidar",
    aoristo: "ξέχασα",
    futuro: "θα ξεχάσω",
    ypotaktiki: "να ξεχάσω",
    imperativo: "",
  },
  {
    id: 109,
    verbo: "φοράω",
    traduccion: "vestir",
    aoristo: "φόρεσα",
    futuro: "θα φορέσω",
    ypotaktiki: "να φορέσω",
    imperativo: "",
  },
  {
    id: 110,
    verbo: "καλώ",
    traduccion: "invitar",
    aoristo: "κάλεσα",
    futuro: "θα καλέσω",
    ypotaktiki: "να καλέσω",
    imperativo: "",
  },
  {
    id: 111,
    verbo: "οδιγώ",
    traduccion: "conducir",
    aoristo: "οδίγησα",
    futuro: "θα οδιγήσω",
    ypotaktiki: "να οδιγήσω",
    imperativo: "",
  },
  {
    id: 112,
    verbo: "διαλέγω",
    traduccion: "elegir",
    aoristo: "διάλεξα",
    futuro: "θα διαλέξω",
    ypotaktiki: "να διαλέξω",
    imperativo: "",
  },
  {
    id: 113,
    verbo: "φτιάχνω",
    traduccion: "preparar, hacer",
    aoristo: "έφτιαξα",
    futuro: "θα φτιάξω",
    ypotaktiki: "να φτιάξω",
    imperativo: "",
  },
  {
    id: 114,
    verbo: "ξυπνάω",
    traduccion: "despertar",
    aoristo: "ξύπνησα",
    futuro: "θα ξυπνήσω",
    ypotaktiki: "να ξυπνήσω",
    imperativo: "",
  },
  {
    id: 115,
    verbo: "ξεπερνάω",
    traduccion: "superar",
    aoristo: "ξεπέρασα",
    futuro: "θα ξεπεράσω",
    ypotaktiki: "να ξεπεράσω",
    imperativo: "",
  },
  {
    id: 116,
    verbo: "περπατάω",
    traduccion: "andar",
    aoristo: "περπάτησα",
    futuro: "θα περπατήσω",
    ypotaktiki: "να περπατήσω",
    imperativo: "",
  },
  {
    id: 117,
    verbo: "αγοράζω",
    traduccion: "comprar",
    aoristo: "αγόρασα",
    futuro: "θα αγοράσω",
    ypotaktiki: "να αγοράσω",
    imperativo: "",
  },
  {
    id: 118,
    verbo: "πληρώνω",
    traduccion: "pagar",
    aoristo: "πλήρωσα",
    futuro: "θα πληρώσω",
    ypotaktiki: "να πληρώσω",
    imperativo: "",
  },
  {
    id: 119,
    verbo: "εισακούω",
    traduccion: "escuchar",
    aoristo: "εισάκουσα",
    futuro: "θα εισακούσω",
    ypotaktiki: "να εισακούσω",
    imperativo: "",
  },
  {
    id: 120,
    verbo: "χρησιμοποιώ",
    traduccion: "utilizar, usar",
    aoristo: "χρησιμόποιησα",
    futuro: "θα χρησιμοποιήσω",
    ypotaktiki: "να χρησιμοποιήσω",
    imperativo: "",
  },
  {
    id: 121,
    verbo: "τρέχω",
    traduccion: "correr",
    aoristo: "έτρεξα",
    futuro: "θα τρέξω",
    ypotaktiki: "να τρέξω",
    imperativo: "",
  },
  {
    id: 122,
    verbo: "μαγειρεύω",
    traduccion: "cocinar",
    aoristo: "μαγείρεψα",
    futuro: "θα μαγειρέψω",
    ypotaktiki: "να μαγειρέψω",
    imperativo: "",
  },
  {
    id: 123,
    verbo: "μαθείνω",
    traduccion: "aprender",
    aoristo: "έμαθα",
    futuro: "θα μάθω",
    ypotaktiki: "να μάθω",
    imperativo: "",
  },
  {
    id: 124,
    verbo: "αρέσω",
    traduccion: "gustar",
    aoristo: "άρεσα",
    futuro: "θα αρέσω",
    ypotaktiki: "να αρέσω",
    imperativo: "",
  },
  {
    id: 125,
    verbo: "πουλώ",
    traduccion: "vender",
    aoristo: "πούλησα",
    futuro: "θα πουλήσω",
    ypotaktiki: "να πουλήσω",
    imperativo: "",
  },
  {
    id: 126,
    verbo: "καίω",
    traduccion: "quemar",
    aoristo: "έκαψα",
    futuro: "θα κάψω",
    ypotaktiki: "να κάψω",
    imperativo: "",
  },
  {
    id: 127,
    verbo: "καίγομαι",
    traduccion: "quemarse",
    aoristo: "κάηκα",
    futuro: "θα κάω",
    ypotaktiki: "να κάω",
    imperativo: "",
  },
  {
    id: 128,
    verbo: "πεινάω",
    traduccion: "tener hambre",
    aoristo: "πείνασα",
    futuro: "θα πεινάσω",
    ypotaktiki: "να πεινάσω",
    imperativo: "",
  },
  {
    id: 129,
    verbo: "λατρεύω",
    traduccion: "adorar",
    aoristo: "λάτρεψα",
    futuro: "θα λατρέψω",
    ypotaktiki: "να λατρέψω",
    imperativo: "",
  },
  {
    id: 130,
    verbo: "συναντάω",
    traduccion: "encontrarse con, reunirse",
    aoristo: "συνάντησα",
    futuro: "θα συναντήσω",
    ypotaktiki: "να συναντήσω",
    imperativo: "",
  },
  {
    id: 131,
    verbo: "τηλεφωνώ",
    traduccion: "llamar por teléfono, telefonear",
    aoristo: "τηλεφώνησα",
    futuro: "θα τηλεφωνήσω",
    ypotaktiki: "να τηλεφωνήσω",
    imperativo: "",
  },
  {
    id: 132,
    verbo: "κόβω",
    traduccion: "cortar",
    aoristo: "έκοψα",
    futuro: "θα κόψω",
    ypotaktiki: "να τκόψω",
    imperativo: "",
  },
  {
    id: 133,
    verbo: "τραβάω",
    traduccion: "tirar",
    aoristo: "τράβηξα",
    futuro: "θα τραβήξω",
    ypotaktiki: "να τραβήξω",
    imperativo: "",
  },
  {
    id: 134,
    verbo: "σπρώχνω",
    traduccion: "empujar",
    aoristo: "έσπρωξα",
    futuro: "θα σπρώξω",
    ypotaktiki: "να σπρώξω",
    imperativo: "",
  },
  {
    id: 135,
    verbo: "μετανιώνω",
    traduccion: "arrepentirse",
    aoristo: "μετάνιωσα",
    futuro: "θα μετανιώσω",
    ypotaktiki: "να μετανιώσω",
    imperativo: "",
  },
  {
    id: 136,
    verbo: "εστιάζω",
    traduccion: "enfocar",
    aoristo: "εστίασα",
    futuro: "θα εστιάσω",
    ypotaktiki: "να εστιάσω",
    imperativo: "",
  },
  {
    id: 137,
    verbo: "φωνάζω",
    traduccion: "gritar",
    aoristo: "φώναξα",
    futuro: "θα φωνάξω",
    ypotaktiki: "να φωνάξω",
    imperativo: "",
  },
  {
    id: 138,
    verbo: "προσέχω",
    traduccion: "cuidar, poner atención",
    aoristo: "πρόσεξα",
    futuro: "θα προσέξω",
    ypotaktiki: "να προσέξω",
    imperativo: "",
  },
  // {
  //   id: 139,
  //   verbo: "είμαι",
  //   traduccion: "ser, estar",
  //   aoristo: "ήμουνα",
  //   futuro: "θα είμαι",
  //   ypotaktiki: "να είμαι",
  //   imperativo: "",
  // },
  {
    id: 140,
    verbo: "συμφωνώ",
    traduccion: "estar de acuerdo",
    aoristo: "συμφώνησα",
    futuro: "θα συμφωνήσω",
    ypotaktiki: "να συμφωνήσω",
    imperativo: "",
  },
  {
    id: 141,
    verbo: "ετοιμάζω",
    traduccion: "preparar, elaborar",
    aoristo: "ετοίμαζα",
    futuro: "θα ετοιμάσω",
    ypotaktiki: "να ετοιμάσω",
    imperativo: "",
  },
  {
    id: 142,
    verbo: "ετοιμάζομαι",
    traduccion: "estar preparado",
    aoristo: "ετοιμάστηκα",
    futuro: "θα ετοιμαστώ",
    ypotaktiki: "να ετοιμαστώ",
    imperativo: "",
  },
  {
    id: 143,
    verbo: "ανησυχώ",
    traduccion: "preocuparse",
    aoristo: "ανησύχησα",
    futuro: "θα ανησυνήσω",
    ypotaktiki: "να ανησυνήσω",
    imperativo: "",
  },
  {
    id: 144,
    verbo: "διορθώνω",
    traduccion: "corregir",
    aoristo: "διόρθωσα",
    futuro: "θα διορθώσω",
    ypotaktiki: "να διορθώσω",
    imperativo: "",
  },
  {
    id: 145,
    verbo: "αργώ",
    traduccion: "llegar tarde",
    aoristo: "άργησα",
    futuro: "θα αργήσω",
    ypotaktiki: "να αργήσω",
    imperativo: "",
  },
  {
    id: 146,
    verbo: "χαίρομαι",
    traduccion: "alegrarse",
    aoristo: "χάρηκα",
    futuro: "θα χαρώ",
    ypotaktiki: "να χαρώ",
    imperativo: "",
  },
  {
    id: 147,
    verbo: "προλαβαίνω",
    traduccion: "alcanzar, llegar",
    aoristo: "πρόλαβα",
    futuro: "θα προλάβω",
    ypotaktiki: "να προλάβω",
    imperativo: "",
  },
  {
    id: 148,
    verbo: "πετάω",
    traduccion: "volar, lanzar",
    aoristo: "πέταξα",
    futuro: "θα πετάξω",
    ypotaktiki: "να πετάξω",
    imperativo: "",
  },
  {
    id: 149,
    verbo: "διψάω",
    traduccion: "tener sed",
    aoristo: "δίψασα",
    futuro: "θα διψάσω",
    ypotaktiki: "να διψάσω",
    imperativo: "",
  },
  {
    id: 150,
    verbo: "κρυώνω",
    traduccion: "tener frío",
    aoristo: "κρύωσα",
    futuro: "θα κρυώσω",
    ypotaktiki: "να κρυώσω",
    imperativo: "",
  },
  {
    id: 151,
    verbo: "νοικιάζω",
    traduccion: "alquilar",
    aoristo: "νοίκιασα",
    futuro: "θα νοικιάσω",
    ypotaktiki: "να νοικιάσω",
    imperativo: "",
  },
  {
    id: 152,
    verbo: "σημαίνω",
    traduccion: "alquilar",
    aoristo: "σήμανα",
    futuro: "θα σημάνω",
    ypotaktiki: "να σημάνω",
    imperativo: "",
  },
  {
    id: 153,
    verbo: "ψωνίζω",
    traduccion: "comprar, hacer la compra",
    aoristo: "ψώνισα",
    futuro: "θα ψωνίσω",
    ypotaktiki: "να ψωνίσω",
    imperativo: "",
  },
  {
    id: 153,
    verbo: "ψωνίζω",
    traduccion: "comprar, hacer la compra",
    aoristo: "ψώνισα",
    futuro: "θα ψωνίσω",
    ypotaktiki: "να ψωνίσω",
    imperativo: "",
  },
  {
    id: 154,
    verbo: "λείπω",
    traduccion: "faltar",
    aoristo: "έλειψα",
    futuro: "θα λείψω",
    ypotaktiki: "να λείψω",
    imperativo: "",
  },
  {
    id: 155,
    verbo: "κερνάω",
    traduccion: "invitar, convidar",
    aoristo: "κέρασα",
    futuro: "θα κεράσω",
    ypotaktiki: "να κεράσω",
    imperativo: "",
  },
  {
    id: 156,
    verbo: "πειράζω",
    traduccion: "molestar, importar",
    aoristo: "πείραξα",
    futuro: "θα πειράξω",
    ypotaktiki: "να πειράξω",
    imperativo: "",
  },
  {
    id: 157,
    verbo: "θεραπεύω",
    traduccion: "curar, sanar",
    aoristo: "θεράπευσα",
    futuro: "θα θεραπεύσω",
    ypotaktiki: "να θεραπεύσω",
    imperativo: "",
  },
  {
    id: 158,
    verbo: "διαφημίζω",
    traduccion: "anunciar",
    aoristo: "διαφήμισα",
    futuro: "θα διαφημίσω",
    ypotaktiki: "να διαφημίσω",
    imperativo: "",
  },
  {
    id: 159,
    verbo: "μπερδεύω",
    traduccion: "confundir",
    aoristo: "μπέρδεψα",
    futuro: "θα μπερδέψω",
    ypotaktiki: "να μπερδέψω",
    imperativo: "",
  },
  {
    id: 160,
    verbo: "ευχαριστώ",
    traduccion: "agradecer",
    aoristo: "ευχαρίστησα",
    futuro: "θα ευχαριστήσω",
    ypotaktiki: "να ευχαριστήσω",
    imperativo: "",
  },
  {
    id: 161,
    verbo: "κρατάω",
    traduccion: "durar",
    aoristo: "κράτησα",
    futuro: "θα κρατήσω",
    ypotaktiki: "να κρατήσω",
    imperativo: "",
  },
  {
    id: 162,
    verbo: "διασκέδαζω",
    traduccion: "divertir",
    aoristo: "διασκέδασα",
    futuro: "θα διασκεδάσω",
    ypotaktiki: "να διασκεδάσω",
    imperativo: "",
  },
  {
    id: 163,
    verbo: "παραγγέλω",
    traduccion: "encargar, pedir a domicilio",
    aoristo: "παράγγειλα",
    futuro: "θα παραγγείλω",
    ypotaktiki: "να παραγγείλω",
    imperativo: "",
  },
  {
    id: 164,
    verbo: "ελπίζω",
    traduccion: "esperar",
    aoristo: "έλπισα",
    futuro: "θα ελπίσω",
    ypotaktiki: "να ελπίσω",
    imperativo: "",
  },
  {
    id: 165,
    verbo: "σημειώνω",
    traduccion: "apuntar, anotar",
    aoristo: "σημείωσα",
    futuro: "θα σημειώσω",
    ypotaktiki: "να σημειώσω",
    imperativo: "",
  },
  {
    id: 166,
    verbo: "εκτιμώ",
    traduccion: "estimar, apreciar, valorar",
    aoristo: "εκτίμησα",
    futuro: "θα εκτιμήσω",
    ypotaktiki: "να εκτιμήσω",
    imperativo: "",
  },
  {
    id: 167,
    verbo: "γιορτάζω",
    traduccion: "celebrar",
    aoristo: "γιόρτασα",
    futuro: "θα γιορτάσω",
    ypotaktiki: "να γιορτάσω",
    imperativo: "",
  },
  {
    id: 168,
    verbo: "παθαίνω",
    traduccion: "celebrar",
    aoristo: "έπαθα",
    futuro: "θα πάθω",
    ypotaktiki: "να πάθω",
    imperativo: "",
  },
  {
    id: 169,
    verbo: "καθαρίζω",
    traduccion: "limpiar",
    aoristo: "καθάρισα",
    futuro: "θα καθαρίσω",
    ypotaktiki: "να καθαρίσω",
    imperativo: "",
  },
  {
    id: 170,
    verbo: "χτενίζω",
    traduccion: "peinar",
    aoristo: "χτένισα",
    futuro: "θα χτενίσω",
    ypotaktiki: "να χτενίσω",
    imperativo: "",
  },
  {
    id: 171,
    verbo: "κρύβω",
    traduccion: "esconder",
    aoristo: "έκρυψα",
    futuro: "θα κρύψω",
    ypotaktiki: "να κρύψω",
    imperativo: "",
  },
  {
    id: 172,
    verbo: "γράφομαι",
    traduccion: "inscribirse",
    aoristo: "γράφτηκα",
    futuro: "θα γραφτώ",
    ypotaktiki: "να γραφτώ",
    imperativo: "",
  },
  {
    id: 173,
    verbo: "χαιρετώ",
    traduccion: "saludar",
    aoristo: "χαιρέτησα",
    futuro: "θα χαιρετήσω",
    ypotaktiki: "να χαιρετήσω",
    imperativo: "",
  },
  {
    id: 174,
    verbo: "μπλέκω",
    traduccion: "implicar",
    aoristo: "έμπλεξα",
    futuro: "θα μπλέξω",
    ypotaktiki: "να μπλέξω",
    imperativo: "",
  },
  {
    id: 175,
    verbo: "προσκαλώ",
    traduccion: "invitar",
    aoristo: "προσκάλεσα",
    futuro: "θα προσκαλέσω",
    ypotaktiki: "να προσκαλέσω",
    imperativo: "",
  },
  {
    id: 176,
    verbo: "φροντίζω",
    traduccion: "cuidar",
    aoristo: "φρόντισα",
    futuro: "θα φροντίσω",
    ypotaktiki: "να φροντίσω",
    imperativo: "",
  },
  {
    id: 177,
    verbo: "θυμίζω",
    traduccion: "recordar algo a alguien",
    aoristo: "θύμισα",
    futuro: "θα θυμίσω",
    ypotaktiki: "να θυμίσω",
    imperativo: "",
  },
  {
    id: 178,
    verbo: "χαλάζω",
    traduccion: "estropear",
    aoristo: "χάλασα",
    futuro: "θα χαλάσω",
    ypotaktiki: "να χαλάσω",
    imperativo: "",
  },
  {
    id: 179,
    verbo: "κλειδώνω",
    traduccion: "cerrar con llave",
    aoristo: "κλείδωσα",
    futuro: "θα κλειδώσω",
    ypotaktiki: "να κλειδώσω",
    imperativo: "",
  },
  {
    id: 180,
    verbo: "πιάνω",
    traduccion: "tocar, coger",
    aoristo: "έπιασα",
    futuro: "θα πιάσω",
    ypotaktiki: "να πιάσω",
    imperativo: "",
  },
  {
    id: 181,
    verbo: "καλύπτω",
    traduccion: "cubrir",
    aoristo: "κάλυψα",
    futuro: "θα καλύψω",
    ypotaktiki: "να καλύψω",
    imperativo: "",
  },
  {
    id: 182,
    verbo: "πνίγω",
    traduccion: "ahogar",
    aoristo: "έπνιξα",
    futuro: "θα πνίξω",
    ypotaktiki: "να πνίξω",
    imperativo: "",
  },
  {
    id: 183,
    verbo: "χτυπάω",
    traduccion: "golpearse, hacerse daño",
    aoristo: "χτύπησα",
    futuro: "θα χτυπήσω",
    ypotaktiki: "να χτυπήσω",
    imperativo: "",
  },
  {
    id: 184,
    verbo: "διώχνω",
    traduccion: "expulsar",
    aoristo: "έδιωξα",
    futuro: "θα διώξω",
    ypotaktiki: "να διώξω",
    imperativo: "",
  },
  {
    id: 185,
    verbo: "μυρίζω",
    traduccion: "oler",
    aoristo: "μύρισα",
    futuro: "θα μυρίσω",
    ypotaktiki: "να μυρίσω",
    imperativo: "",
  },
  {
    id: 186,
    verbo: "βρομάω",
    traduccion: "oler mal",
    aoristo: "βρόμησα",
    futuro: "θα βρομήσω",
    ypotaktiki: "να βρομήσω",
    imperativo: "",
  },
  {
    id: 187,
    verbo: "βράζω",
    traduccion: "hervir",
    aoristo: "έβρασα",
    futuro: "θα βράσω",
    ypotaktiki: "να βράσω",
    imperativo: "",
  },
  {
    id: 188,
    verbo: "τηγανίζω",
    traduccion: "freir",
    aoristo: "τηγάνισα",
    futuro: "θα τηγανίσω",
    ypotaktiki: "να τηγανίσω",
    imperativo: "",
  },
  {
    id: 189,
    verbo: "ρίχνω",
    traduccion: "echar",
    aoristo: "έριξα",
    futuro: "θα ρίξω",
    ypotaktiki: "να ρίξω",
    imperativo: "",
  },
  {
    id: 190,
    verbo: "συνεχίζω",
    traduccion: "continuar",
    aoristo: "συνέχισα",
    futuro: "θα συνεχίσω",
    ypotaktiki: "να συνεχίσω",
    imperativo: "",
  },
  {
    id: 191,
    verbo: "σταματάω",
    traduccion: "parar",
    aoristo: "σταμάτησα",
    futuro: "θα σταματήσω",
    ypotaktiki: "να σταματήσω",
    imperativo: "",
  },
  {
    id: 192,
    verbo: "προτιμάω",
    traduccion: "preferir",
    aoristo: "προτήμισα",
    futuro: "θα προτιμήσω",
    ypotaktiki: "να προτιμήσω",
    imperativo: "",
  },
  {
    id: 193,
    verbo: "λιώνω",
    traduccion: "derretir, disolver",
    aoristo: "έλιωσα",
    futuro: "θα λιώσω",
    ypotaktiki: "να λιώσω",
    imperativo: "",
  },
  {
    id: 194,
    verbo: "προσθέτω",
    traduccion: "añadir",
    aoristo: "πρόσθεσα",
    futuro: "θα προσθέσω",
    ypotaktiki: "να προσθέσω",
    imperativo: "",
  },
  {
    id: 195,
    verbo: "συνηθίζω",
    traduccion: "soler",
    aoristo: "συνήθισα",
    futuro: "θα συνηθίσω",
    ypotaktiki: "να συνηθίσω",
    imperativo: "",
  },
  {
    id: 196,
    verbo: "προτείνω",
    traduccion: "proponer",
    aoristo: "πρότεινα",
    futuro: "θα πρότείνω",
    ypotaktiki: "να πρότείνω",
    imperativo: "",
  },
  {
    id: 197,
    verbo: "επιθυμώ",
    traduccion: "desear",
    aoristo: "επιθύμησα",
    futuro: "θα επιθυμήσω",
    ypotaktiki: "να επιθυμήσω",
    imperativo: "",
  },
  {
    id: 198,
    verbo: "φοιτώ",
    traduccion: "desear",
    aoristo: "επιθύμησα",
    futuro: "θα επιθυμήσω",
    ypotaktiki: "να επιθυμήσω",
    imperativo: "",
  },
  {
    id: 199,
    verbo: "πιστεύω",
    traduccion: "pensar, creer",
    aoristo: "πίστεψα",
    futuro: "θα πιστέψω",
    ypotaktiki: "να πιστέψω",
    imperativo: "",
  },
  {
    id: 200,
    verbo: "επικοινωνώ",
    traduccion: "comunicar",
    aoristo: "επικοινμωνησα",
    futuro: "θα επικοινωνήσω",
    ypotaktiki: "να επικοινωνήσω",
    imperativo: "",
  },
  {
    id: 201,
    verbo: "φοβάμαι",
    traduccion: "tener miedo",
    aoristo: "φοβήθηκα",
    futuro: "θα φοβηθώ",
    ypotaktiki: "να φοβηθώ",
    imperativo: "",
  },
  {
    id: 202,
    verbo: "λυπάμαι",
    traduccion: "sentir tristeza",
    aoristo: "λυπήθηκα",
    futuro: "θα λυπηθώ",
    ypotaktiki: "να λυπηθώ",
    imperativo: "",
  },
  {
    id: 203,
    verbo: "σηκώνω",
    traduccion: "levantar",
    aoristo: "σήκωσα",
    futuro: "θα σηκώσω",
    ypotaktiki: "να σηκώσω",
    imperativo: "",
  },
];
