export const tableDataVerbos = [
  {
    id: 1,
    verbo: "είμαι",
    traduccion: "ser, estar",
    aoristo: "ήμουνα",
    futuro: "θα είμαι",
    ypotaktiki: "να είμαι",
    imperativo: "",
  },
  {
    id: 2,
    verbo: "κάνω",
    traduccion: "hacer",
    aoristo: "έκανα",
    futuro: "θα κάνω",
    ypotaktiki: "να κάνω",
    imperativo: "",
  },
  {
    id: 3,
    verbo: "φέρνω",
    traduccion: "traer",
    aoristo: "έφερα",
    futuro: "θα φέρω",
    ypotaktiki: "να φέρω",
    imperativo: "",
  },
  {
    id: 4,
    verbo: "φεύγω",
    traduccion: "irse, marcharse",
    aoristo: "έφυγα",
    futuro: "θα φύγω",
    ypotaktiki: "να φύγω",
    imperativo: "",
  },
  {
    id: 5,
    verbo: "παίρνω",
    traduccion: "tomar, coger",
    aoristo: "πήρα",
    futuro: "θα πάρω",
    ypotaktiki: "να πάρω",
    imperativo: "",
  },
  {
    id: 6,
    verbo: "περνάω",
    traduccion: "pasar",
    aoristo: "πέρασα",
    futuro: "θα περάσω",
    ypotaktiki: "να περάσω",
    imperativo: "",
  },
  {
    id: 7,
    verbo: "πλένω",
    traduccion: "lavar",
    aoristo: "έπλυνα",
    futuro: "θα πλύνω",
    ypotaktiki: "να πλύνω",
    imperativo: "",
  },
  {
    id: 8,
    verbo: "γίνομαι",
    traduccion: "llegar a ser, convertirse, suceder",
    aoristo: "έγινα",
    futuro: "θα γίνω",
    ypotaktiki: "να γίνω",
    imperativo: "",
  },
  {
    id: 9,
    verbo: "βγαίνω",
    traduccion: "salir",
    aoristo: "βγήκα",
    futuro: "θα βγω",
    ypotaktiki: "να βγω",
    imperativo: "",
  },
  {
    id: 10,
    verbo: "μπάινω",
    traduccion: "entrar",
    aoristo: "μπήκα",
    futuro: "θα μπω",
    ypotaktiki: "να μπω",
    imperativo: "",
  },
  {
    id: 11,
    verbo: "ανεβαίνω",
    traduccion: "subir",
    aoristo: "ανέβηκα",
    futuro: "θα ανεβώ",
    ypotaktiki: "να ανεβώ",
    imperativo: "",
  },
  {
    id: 12,
    verbo: "κατεβαίνω",
    traduccion: "bajar",
    aoristo: "κατέβηκα",
    futuro: "θα κατεβώ",
    ypotaktiki: "να κατεβώ",
    imperativo: "",
  },
  {
    id: 13,
    verbo: "φαίνομαι",
    traduccion: "parecer",
    aoristo: "φάνικα",
    futuro: "θα φάνω",
    ypotaktiki: "να φάνω",
    imperativo: "",
  },
  {
    id: 14,
    verbo: "βάζω",
    traduccion: "poner",
    aoristo: "έβαλα",
    futuro: "θα βάλω",
    ypotaktiki: "να βάλω",
    imperativo: "",
  },
  {
    id: 15,
    verbo: "βγάζω",
    traduccion: "quitar, sacar",
    aoristo: "έβγαλα",
    futuro: "θα βγάλω",
    ypotaktiki: "να βγάλω",
    imperativo: "",
  },
  {
    id: 16,
    verbo: "κάθομαι",
    traduccion: "sentarse, estar sentado",
    aoristo: "κάθισα",
    futuro: "θα καθισώ",
    ypotaktiki: "να καθισώ",
    imperativo: "",
  },
  {
    id: 17,
    verbo: "ονομάζω",
    traduccion: "nombrar",
    aoristo: "ονόμασα",
    futuro: "θα ονομάσω",
    ypotaktiki: "να ονομάσω",
    imperativo: "",
  },
  {
    id: 18,
    verbo: "σκέφτομαι",
    traduccion: "pensar",
    aoristo: "σκεφτηκά",
    futuro: "θα σκεφτώ",
    ypotaktiki: "να σκεφτώ",
    imperativo: "",
  },
  {
    id: 19,
    verbo: "επιστρέφω",
    traduccion: "volver",
    aoristo: "επέστρεψα",
    futuro: "θα επιστρέψω",
    ypotaktiki: "να επιστρέψω",
    imperativo: "",
  },
  {
    id: 20,
    verbo: "ζω",
    traduccion: "vivir",
    aoristo: "έζησα",
    futuro: "θα ζήσω",
    ypotaktiki: "να ζήσω",
    imperativo: "",
  },
];
