export const tableDataVerbos = [
  {
    id: 130,
    verbo: "συναντάω",
    traduccion: "encontrarse con, reunirse",
    aoristo: "συνάντησα",
    futuro: "θα συναντήσω",
    ypotaktiki: "να συναντήσω",
    imperativo: "",
  },
  {
    id: 131,
    verbo: "τηλεφωνώ",
    traduccion: "llamar por teléfono, telefonear",
    aoristo: "τηλεφώνησα",
    futuro: "θα τηλεφωνήσω",
    ypotaktiki: "να τηλεφωνήσω",
    imperativo: "",
  },
  {
    id: 132,
    verbo: "κόβω",
    traduccion: "cortar",
    aoristo: "έκοψα",
    futuro: "θα κόψω",
    ypotaktiki: "να τκόψω",
    imperativo: "",
  },
  {
    id: 133,
    verbo: "τραβάω",
    traduccion: "tirar",
    aoristo: "τράβηξα",
    futuro: "θα τραβήξω",
    ypotaktiki: "να τραβήξω",
    imperativo: "",
  },
  {
    id: 134,
    verbo: "σπρώχνω",
    traduccion: "empujar",
    aoristo: "έσπρωξα",
    futuro: "θα σπρώξω",
    ypotaktiki: "να σπρώξω",
    imperativo: "",
  },
  {
    id: 135,
    verbo: "μετανιώνω",
    traduccion: "arrepentirse",
    aoristo: "μετάνιωσα",
    futuro: "θα μετανιώσω",
    ypotaktiki: "να μετανιώσω",
    imperativo: "",
  },
  {
    id: 136,
    verbo: "εστιάζω",
    traduccion: "enfocar",
    aoristo: "εστίασα",
    futuro: "θα εστιάσω",
    ypotaktiki: "να εστιάσω",
    imperativo: "",
  },
  {
    id: 137,
    verbo: "φωνάζω",
    traduccion: "gritar",
    aoristo: "φώναξα",
    futuro: "θα φωνάξω",
    ypotaktiki: "να φωνάξω",
    imperativo: "",
  },
  {
    id: 138,
    verbo: "προσέχω",
    traduccion: "cuidar, poner atención",
    aoristo: "πρόσεξα",
    futuro: "θα προσέξω",
    ypotaktiki: "να προσέξω",
    imperativo: "",
  },
  {
    id: 140,
    verbo: "συμφωνώ",
    traduccion: "estar de acuerdo",
    aoristo: "συμφώνησα",
    futuro: "θα συμφωνήσω",
    ypotaktiki: "να συμφωνήσω",
    imperativo: "",
  },
  {
    id: 141,
    verbo: "ετοιμάζω",
    traduccion: "preparar, elaborar",
    aoristo: "ετοίμαζα",
    futuro: "θα ετοιμάσω",
    ypotaktiki: "να ετοιμάσω",
    imperativo: "",
  },
  {
    id: 142,
    verbo: "ετοιμάζομαι",
    traduccion: "estar preparado",
    aoristo: "ετοιμάστηκα",
    futuro: "θα ετοιμαστώ",
    ypotaktiki: "να ετοιμαστώ",
    imperativo: "",
  },
  {
    id: 143,
    verbo: "ανησυχώ",
    traduccion: "preocuparse",
    aoristo: "ανησύχησα",
    futuro: "θα ανησυνήσω",
    ypotaktiki: "να ανησυνήσω",
    imperativo: "",
  },
  {
    id: 144,
    verbo: "διορθώνω",
    traduccion: "corregir",
    aoristo: "διόρθωσα",
    futuro: "θα διορθώσω",
    ypotaktiki: "να διορθώσω",
    imperativo: "",
  },
  {
    id: 145,
    verbo: "αργώ",
    traduccion: "llegar tarde",
    aoristo: "άργησα",
    futuro: "θα αργήσω",
    ypotaktiki: "να αργήσω",
    imperativo: "",
  },
  {
    id: 146,
    verbo: "χαίρομαι",
    traduccion: "alegrarse",
    aoristo: "χάρηκα",
    futuro: "θα χαρώ",
    ypotaktiki: "να χαρώ",
    imperativo: "",
  },
  {
    id: 147,
    verbo: "προλαβαίνω",
    traduccion: "alcanzar, llegar",
    aoristo: "πρόλαβα",
    futuro: "θα προλάβω",
    ypotaktiki: "να προλάβω",
    imperativo: "",
  },
  {
    id: 148,
    verbo: "πετάω",
    traduccion: "volar, lanzar",
    aoristo: "πέταξα",
    futuro: "θα πετάξω",
    ypotaktiki: "να πετάξω",
    imperativo: "",
  },
  {
    id: 149,
    verbo: "διψάω",
    traduccion: "tener sed",
    aoristo: "δίψασα",
    futuro: "θα διψάσω",
    ypotaktiki: "να διψάσω",
    imperativo: "",
  },
  {
    id: 150,
    verbo: "κρυώνω",
    traduccion: "tener frío",
    aoristo: "κρύωσα",
    futuro: "θα κρυώσω",
    ypotaktiki: "να κρυώσω",
    imperativo: "",
  },
  {
    id: 151,
    verbo: "νοικιάζω",
    traduccion: "alquilar",
    aoristo: "νοίκιασα",
    futuro: "θα νοικιάσω",
    ypotaktiki: "να νοικιάσω",
    imperativo: "",
  },
  {
    id: 152,
    verbo: "σημαίνω",
    traduccion: "alquilar",
    aoristo: "σήμανα",
    futuro: "θα σημάνω",
    ypotaktiki: "να σημάνω",
    imperativo: "",
  },
  {
    id: 153,
    verbo: "ψωνίζω",
    traduccion: "comprar, hacer la compra",
    aoristo: "ψώνισα",
    futuro: "θα ψωνίσω",
    ypotaktiki: "να ψωνίσω",
    imperativo: "",
  },
  {
    id: 153,
    verbo: "ψωνίζω",
    traduccion: "comprar, hacer la compra",
    aoristo: "ψώνισα",
    futuro: "θα ψωνίσω",
    ypotaktiki: "να ψωνίσω",
    imperativo: "",
  },
  {
    id: 154,
    verbo: "λείπω",
    traduccion: "faltar",
    aoristo: "έλειψα",
    futuro: "θα λείψω",
    ypotaktiki: "να λείψω",
    imperativo: "",
  },
  {
    id: 155,
    verbo: "κερνάω",
    traduccion: "invitar, convidar",
    aoristo: "κέρασα",
    futuro: "θα κεράσω",
    ypotaktiki: "να κεράσω",
    imperativo: "",
  },
  {
    id: 156,
    verbo: "πειράζω",
    traduccion: "molestar, importar",
    aoristo: "πείραξα",
    futuro: "θα πειράξω",
    ypotaktiki: "να πειράξω",
    imperativo: "",
  },
  {
    id: 157,
    verbo: "θεραπεύω",
    traduccion: "curar, sanar",
    aoristo: "θεράπευσα",
    futuro: "θα θεραπεύσω",
    ypotaktiki: "να θεραπεύσω",
    imperativo: "",
  },
  {
    id: 158,
    verbo: "διαφημίζω",
    traduccion: "anunciar",
    aoristo: "διαφήμισα",
    futuro: "θα διαφημίσω",
    ypotaktiki: "να διαφημίσω",
    imperativo: "",
  },
  {
    id: 159,
    verbo: "μπερδεύω",
    traduccion: "confundir",
    aoristo: "μπέρδεψα",
    futuro: "θα μπερδέψω",
    ypotaktiki: "να μπερδέψω",
    imperativo: "",
  },
  {
    id: 160,
    verbo: "ευχαριστώ",
    traduccion: "agradecer",
    aoristo: "ευχαρίστησα",
    futuro: "θα ευχαριστήσω",
    ypotaktiki: "να ευχαριστήσω",
    imperativo: "",
  },
  {
    id: 161,
    verbo: "κρατάω",
    traduccion: "durar",
    aoristo: "κράτησα",
    futuro: "θα κρατήσω",
    ypotaktiki: "να κρατήσω",
    imperativo: "",
  },
  {
    id: 162,
    verbo: "διασκέδαζω",
    traduccion: "divertir",
    aoristo: "διασκέδασα",
    futuro: "θα διασκεδάσω",
    ypotaktiki: "να διασκεδάσω",
    imperativo: "",
  },
  {
    id: 163,
    verbo: "παραγγέλω",
    traduccion: "encargar, pedir a domicilio",
    aoristo: "παράγγειλα",
    futuro: "θα παραγγείλω",
    ypotaktiki: "να παραγγείλω",
    imperativo: "",
  },
  {
    id: 164,
    verbo: "ελπίζω",
    traduccion: "esperar",
    aoristo: "έλπισα",
    futuro: "θα ελπίσω",
    ypotaktiki: "να ελπίσω",
    imperativo: "",
  },
  {
    id: 165,
    verbo: "σημειώνω",
    traduccion: "apuntar, anotar",
    aoristo: "σημείωσα",
    futuro: "θα σημειώσω",
    ypotaktiki: "να σημειώσω",
    imperativo: "",
  },
  {
    id: 166,
    verbo: "εκτιμώ",
    traduccion: "estimar, apreciar, valorar",
    aoristo: "εκτίμησα",
    futuro: "θα εκτιμήσω",
    ypotaktiki: "να εκτιμήσω",
    imperativo: "",
  },
  {
    id: 167,
    verbo: "γιορτάζω",
    traduccion: "celebrar",
    aoristo: "γιόρτασα",
    futuro: "θα γιορτάσω",
    ypotaktiki: "να γιορτάσω",
    imperativo: "",
  },
  {
    id: 168,
    verbo: "παθαίνω",
    traduccion: "celebrar",
    aoristo: "έπαθα",
    futuro: "θα πάθω",
    ypotaktiki: "να πάθω",
    imperativo: "",
  },
  {
    id: 169,
    verbo: "καθαρίζω",
    traduccion: "limpiar",
    aoristo: "καθάρισα",
    futuro: "θα καθαρίσω",
    ypotaktiki: "να καθαρίσω",
    imperativo: "",
  },
  {
    id: 170,
    verbo: "χτενίζω",
    traduccion: "peinar",
    aoristo: "χτένισα",
    futuro: "θα χτενίσω",
    ypotaktiki: "να χτενίσω",
    imperativo: "",
  },
  {
    id: 171,
    verbo: "κρύβω",
    traduccion: "esconder",
    aoristo: "έκρυψα",
    futuro: "θα κρύψω",
    ypotaktiki: "να κρύψω",
    imperativo: "",
  },
  {
    id: 172,
    verbo: "γράφομαι",
    traduccion: "inscribirse",
    aoristo: "γράφτηκα",
    futuro: "θα γραφτώ",
    ypotaktiki: "να γραφτώ",
    imperativo: "",
  },
  {
    id: 173,
    verbo: "χαιρετώ",
    traduccion: "saludar",
    aoristo: "χαιρέτησα",
    futuro: "θα χαιρετήσω",
    ypotaktiki: "να χαιρετήσω",
    imperativo: "",
  },
  {
    id: 174,
    verbo: "μπλέκω",
    traduccion: "implicar",
    aoristo: "έμπλεξα",
    futuro: "θα μπλέξω",
    ypotaktiki: "να μπλέξω",
    imperativo: "",
  },
  {
    id: 175,
    verbo: "προσκαλώ",
    traduccion: "invitar",
    aoristo: "προσκάλεσα",
    futuro: "θα προσκαλέσω",
    ypotaktiki: "να προσκαλέσω",
    imperativo: "",
  },
  {
    id: 176,
    verbo: "φροντίζω",
    traduccion: "cuidar",
    aoristo: "φρόντισα",
    futuro: "θα φροντίσω",
    ypotaktiki: "να φροντίσω",
    imperativo: "",
  },
  {
    id: 177,
    verbo: "θυμίζω",
    traduccion: "recordar algo a alguien",
    aoristo: "θύμισα",
    futuro: "θα θυμίσω",
    ypotaktiki: "να θυμίσω",
    imperativo: "",
  },
  {
    id: 178,
    verbo: "χαλάζω",
    traduccion: "estropear",
    aoristo: "χάλασα",
    futuro: "θα χαλάσω",
    ypotaktiki: "να χαλάσω",
    imperativo: "",
  },
  {
    id: 179,
    verbo: "κλειδώνω",
    traduccion: "cerrar con llave",
    aoristo: "κλείδωσα",
    futuro: "θα κλειδώσω",
    ypotaktiki: "να κλειδώσω",
    imperativo: "",
  },
  {
    id: 180,
    verbo: "πιάνω",
    traduccion: "tocar, coger",
    aoristo: "έπιασα",
    futuro: "θα πιάσω",
    ypotaktiki: "να πιάσω",
    imperativo: "",
  },
  {
    id: 181,
    verbo: "καλύπτω",
    traduccion: "cubrir",
    aoristo: "κάλυψα",
    futuro: "θα καλύψω",
    ypotaktiki: "να καλύψω",
    imperativo: "",
  },
  {
    id: 182,
    verbo: "πνίγω",
    traduccion: "ahogar",
    aoristo: "έπνιξα",
    futuro: "θα πνίξω",
    ypotaktiki: "να πνίξω",
    imperativo: "",
  },
  {
    id: 183,
    verbo: "χτυπάω",
    traduccion: "golpearse, hacerse daño",
    aoristo: "χτύπησα",
    futuro: "θα χτυπήσω",
    ypotaktiki: "να χτυπήσω",
    imperativo: "",
  },
  {
    id: 184,
    verbo: "διώχνω",
    traduccion: "expulsar",
    aoristo: "έδιωξα",
    futuro: "θα διώξω",
    ypotaktiki: "να διώξω",
    imperativo: "",
  },
  {
    id: 185,
    verbo: "μυρίζω",
    traduccion: "oler",
    aoristo: "μύρισα",
    futuro: "θα μυρίσω",
    ypotaktiki: "να μυρίσω",
    imperativo: "",
  },
  {
    id: 186,
    verbo: "βρομάω",
    traduccion: "oler mal",
    aoristo: "βρόμησα",
    futuro: "θα βρομήσω",
    ypotaktiki: "να βρομήσω",
    imperativo: "",
  },
  {
    id: 187,
    verbo: "βράζω",
    traduccion: "hervir",
    aoristo: "έβρασα",
    futuro: "θα βράσω",
    ypotaktiki: "να βράσω",
    imperativo: "",
  },
  {
    id: 188,
    verbo: "τηγανίζω",
    traduccion: "freir",
    aoristo: "τηγάνισα",
    futuro: "θα τηγανίσω",
    ypotaktiki: "να τηγανίσω",
    imperativo: "",
  },
  {
    id: 189,
    verbo: "ρίχνω",
    traduccion: "echar",
    aoristo: "έριξα",
    futuro: "θα ρίξω",
    ypotaktiki: "να ρίξω",
    imperativo: "",
  },
  {
    id: 190,
    verbo: "συνεχίζω",
    traduccion: "continuar",
    aoristo: "συνέχισα",
    futuro: "θα συνεχίσω",
    ypotaktiki: "να συνεχίσω",
    imperativo: "",
  },
  {
    id: 191,
    verbo: "σταματάω",
    traduccion: "parar",
    aoristo: "σταμάτησα",
    futuro: "θα σταματήσω",
    ypotaktiki: "να σταματήσω",
    imperativo: "",
  },
  {
    id: 192,
    verbo: "προτιμάω",
    traduccion: "preferir",
    aoristo: "προτήμισα",
    futuro: "θα προτιμήσω",
    ypotaktiki: "να προτιμήσω",
    imperativo: "",
  },
  {
    id: 193,
    verbo: "λιώνω",
    traduccion: "derretir, disolver",
    aoristo: "έλιωσα",
    futuro: "θα λιώσω",
    ypotaktiki: "να λιώσω",
    imperativo: "",
  },
  {
    id: 194,
    verbo: "προσθέτω",
    traduccion: "añadir",
    aoristo: "πρόσθεσα",
    futuro: "θα προσθέσω",
    ypotaktiki: "να προσθέσω",
    imperativo: "",
  },
  {
    id: 195,
    verbo: "συνηθίζω",
    traduccion: "soler",
    aoristo: "συνήθισα",
    futuro: "θα συνηθίσω",
    ypotaktiki: "να συνηθίσω",
    imperativo: "",
  },
  {
    id: 196,
    verbo: "προτείνω",
    traduccion: "proponer",
    aoristo: "πρότεινα",
    futuro: "θα πρότείνω",
    ypotaktiki: "να πρότείνω",
    imperativo: "",
  },
  {
    id: 197,
    verbo: "επιθυμώ",
    traduccion: "desear",
    aoristo: "επιθύμησα",
    futuro: "θα επιθυμήσω",
    ypotaktiki: "να επιθυμήσω",
    imperativo: "",
  },
  {
    id: 198,
    verbo: "φοιτώ",
    traduccion: "desear",
    aoristo: "επιθύμησα",
    futuro: "θα επιθυμήσω",
    ypotaktiki: "να επιθυμήσω",
    imperativo: "",
  },
  {
    id: 199,
    verbo: "πιστεύω",
    traduccion: "pensar, creer",
    aoristo: "πίστεψα",
    futuro: "θα πιστέψω",
    ypotaktiki: "να πιστέψω",
    imperativo: "",
  },
  {
    id: 200,
    verbo: "επικοινωνώ",
    traduccion: "comunicar",
    aoristo: "επικοινμωνησα",
    futuro: "θα επικοινωνήσω",
    ypotaktiki: "να επικοινωνήσω",
    imperativo: "",
  },
  {
    id: 201,
    verbo: "φοβάμαι",
    traduccion: "tener miedo",
    aoristo: "φοβήθηκα",
    futuro: "θα φοβηθώ",
    ypotaktiki: "να φοβηθώ",
    imperativo: "",
  },
  {
    id: 202,
    verbo: "λυπάμαι",
    traduccion: "sentir tristeza",
    aoristo: "λυπήθηκα",
    futuro: "θα λυπηθώ",
    ypotaktiki: "να λυπηθώ",
    imperativo: "",
  },
  {
    id: 203,
    verbo: "σηκώνω",
    traduccion: "levantar",
    aoristo: "σήκωσα",
    futuro: "θα σηκώσω",
    ypotaktiki: "να σηκώσω",
    imperativo: "",
  },
];
